package com.miguelcr.app.localdb;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.miguelcr.app.localdb.Airline;
import com.miguelcr.app.localdb.Vuelo;

import com.miguelcr.app.localdb.AirlineDao;
import com.miguelcr.app.localdb.VueloDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig airlineDaoConfig;
    private final DaoConfig vueloDaoConfig;

    private final AirlineDao airlineDao;
    private final VueloDao vueloDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        airlineDaoConfig = daoConfigMap.get(AirlineDao.class).clone();
        airlineDaoConfig.initIdentityScope(type);

        vueloDaoConfig = daoConfigMap.get(VueloDao.class).clone();
        vueloDaoConfig.initIdentityScope(type);

        airlineDao = new AirlineDao(airlineDaoConfig, this);
        vueloDao = new VueloDao(vueloDaoConfig, this);

        registerDao(Airline.class, airlineDao);
        registerDao(Vuelo.class, vueloDao);
    }
    
    public void clear() {
        airlineDaoConfig.getIdentityScope().clear();
        vueloDaoConfig.getIdentityScope().clear();
    }

    public AirlineDao getAirlineDao() {
        return airlineDao;
    }

    public VueloDao getVueloDao() {
        return vueloDao;
    }

}
