package com.miguelcr.app.localdb;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "VUELO".
 */
@Entity
public class Vuelo {

    @Id(autoincrement = true)
    private Long id;

    @NotNull
    private String codigoVuelo;

    @NotNull
    private java.util.Date fechaHora;
    private long idAirline;

    @Generated
    public Vuelo() {
    }

    public Vuelo(Long id) {
        this.id = id;
    }

    @Generated
    public Vuelo(Long id, String codigoVuelo, java.util.Date fechaHora, long idAirline) {
        this.id = id;
        this.codigoVuelo = codigoVuelo;
        this.fechaHora = fechaHora;
        this.idAirline = idAirline;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @NotNull
    public String getCodigoVuelo() {
        return codigoVuelo;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCodigoVuelo(@NotNull String codigoVuelo) {
        this.codigoVuelo = codigoVuelo;
    }

    @NotNull
    public java.util.Date getFechaHora() {
        return fechaHora;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setFechaHora(@NotNull java.util.Date fechaHora) {
        this.fechaHora = fechaHora;
    }

    public long getIdAirline() {
        return idAirline;
    }

    public void setIdAirline(long idAirline) {
        this.idAirline = idAirline;
    }

}
